### ISSUE TITLE
stderr vs. stdout

### ISSUE THREAD

**Issue by hrobeers** [mattsta/erlang-stdinout-pool#10]
Currently stderr is handled the same way as stdout by just returning the Value.

Error handling would be cleaner if:
* stderr is returned as {error, Value}
* stdout is returned as {ok, Value}

I'll try to fix this. But this will break backwards compatibility.

**Comment by hrobeers** [comment]
I can't seem to find a way to differentiate between stdout and stderr on the Erlang side.
Maybe you have an idea?

**Comment by hrobeers** [comment]
I'm thinking of prefixing the stderr output by the ASCII/UTF-8 PU1 control character (http://www.aivosto.com/vbtips/control-characters.html#PU1) to differentiate on the Erlang side.

While reverse-engineering the stdin_forcer.c file, I noticed that line 78 is never executed. You can test this by adding "assert(0);" in the loop:
```c
 while (read(PARENT_READ, &buf, 1) > 0) {
  assert(0);
  unused = write(STDOUT_FILENO, &buf, 1); /* Vomit forth our output on STDOUT */
}
```
it will still run as expected.

**Comment by hrobeers** [comment]
I completed my fix for this issue. I'm just cleaning up some code and updating the unit tests.

Please note that this will break the return types of the send and pipe methods, so probably something for the 2.0 milestone.

Pull request will follow soon.

**Comment by mattsta** [comment]
Thanks for the fixes!  It's completely okay to break the API here when introducing new (better) behavior.

The original implementation was designed around one use case, but it should be more robust now.

I look forward to seeing what you came up with  :)
