### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by hrobeers** [mattsta/erlang-stdinout-pool#9]
It is not clear to me under which license you release this code.

**Comment by mattsta** [comment]
Thanks for pushing this forward.  Fixed in https://github.com/mattsta/erlang-stdinout-pool/commit/193f2dd6b7a3de5fa2c77d206a8e46e439fd20d8

All contributions welcome with no restrictions on any future usage!

**Comment by hrobeers** [comment]
Thanks!

I noticed that your other repos don't include a LICENSE file either.
It doesn't matter for me now, since I'm testing only this one right now.

I just wanted to bring this to your attention.
